### ISSUE TITLE
error on installing plugin

### ISSUE THREAD

**Issue by hcimadomo-procsi** [ryanblenis/MeshCentral-EventLog#8]
Hello, when i want install the plugin, i have foolowing error. Can you help me ?
BR
trace error in server:
Error instantiating new plugin:  { Error: Cannot find module 'promise'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/app/meshcentral/meshcentral-data/plugins/eventlog/db.js:9:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' }
Error ocurred while running plugin hookeventlog:hook_agentCoreIsStable (TypeError: Cannot read property 'getConfigFor' of null)
Error ocurred while running plugin hookeventlog:hook_agentCoreIsStable (TypeError: Cannot read property 'getConfigFor' of null)
Error ocurred while running plugin hookeventlog:hook_agentCoreIsStable (TypeError: Cannot read property 'getConfigFor' of null)

**Comment by usafirstamengm** [comment]
Same here. Did you resolve this. I think I need to install via NPM but not sure

**Comment by pierrecorsini** [comment]
Same here.

**Comment by pierrecorsini** [comment]
Well, I solved the issue by installing with `npm install` the modules `nedb` and `promise` (from the main meshcentral directory).

Unfortunately I do not know how to push a fix (no idea how the npm plugin dependencies works).

**EDIT**
Reaching new errors when saving plugin specific settings.

```
Node.js v18.13.0
Error: Command failed: /usr/bin/node /home/debian/node_modules/meshcentral --launch 123654
/home/debian/node_modules/meshcentral/meshuser.js:4550
                    } catch (ex) { console.log('Error loading plugin handler (' + e + ')'); }
                                                                                  ^

ReferenceError: e is not defined
    at WebSocket.processWebSocketData (/home/debian/node_modules/meshcentral/meshuser.js:4550:83)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/home/debian/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (/home/debian/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/home/debian/node_modules/ws/lib/receiver.js:346:17)
    at Receiver.startLoop (/home/debian/node_modules/ws/lib/receiver.js:133:22)
    at Receiver._write (/home/debian/node_modules/ws/lib/receiver.js:69:10)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)

Node.js v18.13.0

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:525:35)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: '/usr/bin/node /home/debian/node_modules/meshcentral --launch 123654'
}
ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...

```
